SELECT temp.Year, temp.DTA_VALEUR AS Annual_Temperature, co2.Total_Valeur AS CO2_Consumption
FROM 
    (SELECT YEAR(DAT_DATE) AS Year, DTA_VALEUR
     FROM T_DATA_DTA
     INNER JOIN T_PAYS_PYS ON T_DATA_DTA.PYS_ID = T_PAYS_PYS.PYS_ID
     INNER JOIN T_DATE_DAT ON T_DATA_DTA.DAT_ID = T_DATE_DAT.DAT_ID
     WHERE DTA_NOM = 'Annual Temperature' AND PYS_NOM = 'China'
    ) AS temp
INNER JOIN 
    (SELECT YEAR(DAT_DATE) AS Year, SUM(CAST(DTA_VALEUR AS float)) AS Total_Valeur
     FROM T_DATA_DTA
     INNER JOIN T_PAYS_PYS ON T_DATA_DTA.PYS_ID = T_PAYS_PYS.PYS_ID
     INNER JOIN T_DATE_DAT ON T_DATA_DTA.DAT_ID = T_DATE_DAT.DAT_ID
     WHERE DTA_UNITE = 'CO2' AND PYS_NOM = 'China'
     GROUP BY YEAR(DAT_DATE)
    ) AS co2
ON temp.Year = co2.Year
ORDER BY temp.Year;