SELECT DAT_DATE, PYS_NOM, DTA_VALEUR 
FROM T_DATA_DTA 
INNER JOIN T_PAYS_PYS ON T_DATA_DTA.PYS_ID = T_PAYS_PYS.PYS_ID 
INNER JOIN T_DATE_DAT ON T_DATE_DAT.DAT_ID = T_DATA_DTA.DAT_ID 
WHERE (PYS_NOM = 'Germany' OR PYS_NOM = 'China' ) 
	AND DTA_NOM = 'GDP'  
	AND DAT_DATE >= '1990-01-01' 
	AND DAT_DATE <= '2024-12-31' 
ORDER BY T_DATE_DAT.DAT_DATE