--INSERT INTO T_REGION_REG(REG_NOM) 
--VALUES ('Europe');

--INSERT INTO T_PAYS_PYS(REG_ID, PYS_NOM)
--SELECT REG_ID, 'FRANCE' FROM T_REGION_REG WHERE REG_NOM = 'Europe';


--INSERT INTO T_DATA_DTA (PYS_ID, DTA_DATE, DTA_VALEUR, DTA_NOM, DTA_UNITE)
--SELECT PYS_ID, '2024-06-06 00:00:00',123.45,'Nom de Donnée','Unité' FROM T_PAYS_PYS WHERE PYS_NOM = 'FRANCE';

--INSERT into T_ENERGY_EGY(EGY_NOM)
--values ('GAZ')

--INSERT INTO COMPORTER (EGY_ID, DTA_ID)
--SELECT 
--    (SELECT EGY_ID FROM T_ENERGY_EGY WHERE EGY_NOM = 'GAZ'),
--    (SELECT DTA_ID FROM T_DATA_DTA WHERE DTA_NOM = 'Nom de Donnée' AND PYS_ID = (SELECT PYS_ID FROM T_PAYS_PYS WHERE PYS_NOM = 'FRANCE'));
use master
go
Use SAE_TEAM5
go
select * from T_REGION_REG
select * from T_PAYS_PYS
select * from T_DATA_DTA
select * from T_DATE_DAT
select * from T_ACTIVITY_ACT

select DTA_NOM, DTA_UNITE, PYS_NOM, DAT_DATE, DTA_VALEUR
from T_DATA_DTA
inner join T_PAYS_PYS on T_DATA_DTA.PYS_ID=T_PAYS_PYS.PYS_ID
inner join T_DATE_DAT on T_DATA_DTA.DAT_ID = T_DATE_DAT.DAT_ID
where DTA_NOM = 'Population' and PYS_NOM = 'France'

SELECT DTA_NOM, DTA_UNITE, PYS_NOM, YEAR(DAT_DATE) AS Year, SUM(CAST(DTA_VALEUR AS float)) AS Total_Valeur
FROM T_DATA_DTA
INNER JOIN 
    T_PAYS_PYS ON T_DATA_DTA.PYS_ID = T_PAYS_PYS.PYS_ID
INNER JOIN 
    T_DATE_DAT ON T_DATA_DTA.DAT_ID = T_DATE_DAT.DAT_ID
WHERE DTA_UNITE = 'CO2' AND PYS_NOM = 'France'
GROUP BY  DTA_NOM, DTA_UNITE, PYS_NOM, YEAR(DAT_DATE)
ORDER BY Year;

--Température en fonction du co2
select * from T_ENERGY_EGY
select DTA_NOM, DTA_UNITE, PYS_NOM, DAT_DATE, DTA_VALEUR
from T_DATA_DTA
inner join T_PAYS_PYS on T_DATA_DTA.PYS_ID=T_PAYS_PYS.PYS_ID
inner join T_DATE_DAT on T_DATA_DTA.DAT_ID = T_DATE_DAT.DAT_ID
where DTA_NOM = 'Annual Temperature' and PYS_NOM = 'Germany'

SELECT DTA_NOM, DTA_UNITE, PYS_NOM, YEAR(DAT_DATE) AS Year, SUM(CAST(DTA_VALEUR AS float)) AS Total_Valeur
FROM T_DATA_DTA
INNER JOIN 
    T_PAYS_PYS ON T_DATA_DTA.PYS_ID = T_PAYS_PYS.PYS_ID
INNER JOIN 
    T_DATE_DAT ON T_DATA_DTA.DAT_ID = T_DATE_DAT.DAT_ID
WHERE DTA_UNITE = 'CO2' AND PYS_NOM = 'Germany'
GROUP BY  DTA_NOM, DTA_UNITE, PYS_NOM, YEAR(DAT_DATE)
ORDER BY Year;

---Co2 chine USA et temp mondiale
SELECT DTA_NOM, DTA_UNITE, YEAR(DAT_DATE) AS Year, avg(CAST(DTA_VALEUR AS float)) AS Total_Valeur
FROM T_DATA_DTA
INNER JOIN T_PAYS_PYS ON T_DATA_DTA.PYS_ID = T_PAYS_PYS.PYS_ID
INNER JOIN T_DATE_DAT ON T_DATA_DTA.DAT_ID = T_DATE_DAT.DAT_ID
WHERE DTA_NOM = 'Annual Temperature'
GROUP BY  DTA_NOM, DTA_UNITE, YEAR(DAT_DATE) ORDER BY Year;


SELECT DTA_NOM, DTA_UNITE, PYS_NOM, YEAR(DAT_DATE) AS Year, SUM(CAST(DTA_VALEUR AS float)) AS Total_Valeur
FROM T_DATA_DTA
INNER JOIN 
    T_PAYS_PYS ON T_DATA_DTA.PYS_ID = T_PAYS_PYS.PYS_ID
INNER JOIN 
    T_DATE_DAT ON T_DATA_DTA.DAT_ID = T_DATE_DAT.DAT_ID
WHERE DTA_UNITE = 'CO2' AND PYS_NOM = 'United States of America' AND PYS_NOM = 'China'
GROUP BY  DTA_NOM, DTA_UNITE, PYS_NOM, YEAR(DAT_DATE)
ORDER BY Year;
---




USE SAE_TEAM5;
GO
Use master
go
-- Créez l'utilisateur de la base de données s'il n'existe pas
--IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'etd05')
--BEGIN
--  CREATE USER etd05 FOR LOGIN etd05;
--END;
--GO

-- Attribuez les autorisations nécessaires à l'utilisateur
--ALTER ROLE db_owner ADD MEMBER etd05;
--GO
